// Import all models to ensure they are registered with Mongoose
// This is especially important in development mode with Turbopack

import "./User";
import "./College";
import "./News";
import "./NewsCategory";
import "./Country";
import "./CountryMaster";
import "./State";
import "./District";
import "./Ownership";
import "./Affiliation";
import "./ApprovedThrough";
import "./CollegeFacility";
import "./HospitalFacility";
import "./HostelFacility";
import "./Course";
import "./CourseDuration";
import "./CollegeCourseAllocation";
import "./CollegeRanking";
import "./CollegeDistanceMeter";
import "./CollegeReview";
import "./Degree";
import "./Exam";
import "./ExamLevel";
import "./ExamType";
import "./Ranking";
import "./Stream";
import "./Testimonial";
import "./FacilitySection";
import "./Blog";
import "./BlogCategory";
import "./Page";
import "./PageCategory";
import "./Contact";
import "./EligibilityCheck";
import "./NewsletterSubscription";
import "./Language";
import "./DistanceMeter";
import "./FooterSection";

// Re-export all models for convenience
export { default as User } from "./User";
export { default as College } from "./College";
export { default as News } from "./News";
export { default as NewsCategory } from "./NewsCategory";
export { default as Country } from "./Country";
export { default as CountryMaster } from "./CountryMaster";
export { default as State } from "./State";
export { default as District } from "./District";
export { default as Ownership } from "./Ownership";
export { default as Affiliation } from "./Affiliation";
export { default as ApprovedThrough } from "./ApprovedThrough";
export { default as CollegeFacility } from "./CollegeFacility";
export { default as HospitalFacility } from "./HospitalFacility";
export { default as HostelFacility } from "./HostelFacility";
export { default as Course } from "./Course";
export { default as CourseDuration } from "./CourseDuration";
export { default as CollegeCourseAllocation } from "./CollegeCourseAllocation";
export { default as CollegeRanking } from "./CollegeRanking";
export { default as CollegeDistanceMeter } from "./CollegeDistanceMeter";
export { default as CollegeReview } from "./CollegeReview";
export { default as Degree } from "./Degree";
export { default as Exam } from "./Exam";
export { default as ExamLevel } from "./ExamLevel";
export { default as ExamType } from "./ExamType";
export { default as Ranking } from "./Ranking";
export { default as Stream } from "./Stream";
export { default as Testimonial } from "./Testimonial";
export { default as FacilitySection } from "./FacilitySection";
export { default as Blog } from "./Blog";
export { default as BlogCategory } from "./BlogCategory";
export { default as Page } from "./Page";
export { default as PageCategory } from "./PageCategory";
export { default as Contact } from "./Contact";
export { default as EligibilityCheck } from "./EligibilityCheck";
export { default as NewsletterSubscription } from "./NewsletterSubscription";
export { default as Language } from "./Language";
export { default as DistanceMeter } from "./DistanceMeter";
export { default as FooterSection } from "./FooterSection";
